"""add foreign key to onboarding

Revision ID: 30564eec448d
Revises: e3d908b6dfec
Create Date: 2024-10-03 10:48:12.720064

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '30564eec448d'
down_revision = 'e3d908b6dfec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('onboardings', sa.Column('employee_id', sa.Integer(), nullable=True))
    op.create_foreign_key(op.f('fk_onboardings_employee_id_employees'), 'onboardings', 'employees', ['employee_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_onboardings_employee_id_employees'), 'onboardings', type_='foreignkey')
    op.drop_column('onboardings', 'employee_id')
    # ### end Alembic commands ###
